# Generated by Django 4.0.4 on 2022-05-15 17:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Jinsi')),
            ],
            options={
                'verbose_name': 'Jins ',
                'verbose_name_plural': 'Jinslar',
            },
        ),
        migrations.CreateModel(
            name='Millat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Millati')),
            ],
            options={
                'verbose_name': 'Millat ',
                'verbose_name_plural': 'Millatlar',
            },
        ),
        migrations.CreateModel(
            name='TalimShakli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ta`lim shakli')),
            ],
            options={
                'verbose_name': 'Ta`lim Shakli ',
                'verbose_name_plural': 'Ta`lim Shakllari',
            },
        ),
        migrations.CreateModel(
            name='TalimTili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ta`lim Tili')),
            ],
            options={
                'verbose_name': 'Ta`lim Tili ',
                'verbose_name_plural': 'Ta`lim Tillari',
            },
        ),
        migrations.CreateModel(
            name='TalimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ta`lim Turi')),
            ],
            options={
                'verbose_name': 'Ta`lim Turi ',
                'verbose_name_plural': 'Ta`lim Turlari',
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Viloyat ',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='YonalishOTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='OTM yo`nalish nomi')),
                ('talim_shakli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.talimshakli', verbose_name='Ta`lim Shakli')),
                ('talim_tili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.talimtili', verbose_name='Ta`lim tili')),
                ('talim_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.talimturi', verbose_name='Ta`lim turi')),
            ],
            options={
                'verbose_name': 'OTM Yo`nalish ',
                'verbose_name_plural': 'OTM Yo`nalishlar',
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Tuman')),
                ('viloyat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.viloyat', verbose_name='viloyat')),
            ],
            options={
                'verbose_name': 'Tuman ',
                'verbose_name_plural': 'Tumanlar',
            },
        ),
        migrations.CreateModel(
            name='Pasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jshir', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Ma`lumot xato kiritildi!', regex='^[0-9]{14}')], verbose_name='JSHIR')),
                ('familiya', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=30)),
                ('sharif', models.CharField(max_length=30)),
                ('tug_sana', models.DateField()),
                ('pass_seriya', models.CharField(max_length=2, verbose_name='Passport seriyasi')),
                ('pass_raqam', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Ma`lumot xato kiritildi!', regex='^[0-9]{7}')], verbose_name='Passport seriyasi')),
                ('pass_berilgan_sana', models.DateField()),
                ('doimiy_manzil', models.CharField(blank=True, help_text='Obod ko`cha 5-uy', max_length=250, null=True, verbose_name='Doimiy yashash manzili')),
                ('photo', models.ImageField(help_text='Maksimum fayl hajmi 2Mb', upload_to='photos/%Y', validators=[myapp.models.validate_image], verbose_name='Rasm')),
                ('telefon_raqam', models.CharField(help_text='Telegram raqam', max_length=9, validators=[django.core.validators.RegexValidator(message='Ma`lumot xato kiritildi!', regex='^[0-9]{9}')])),
                ('telefon_raqam_2', models.CharField(blank=True, help_text='Qoshimcha raqam, Majburiy emas', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Ma`lumot xato kiritildi!', regex='^[0-9]{9}')], verbose_name='Qo`shimcha raqam')),
                ('qushulgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Qo`shilgan sana')),
                ('yangilangan_sana', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('doimiy_tuman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='myapp.tuman', verbose_name='Doimiy yashash tumani')),
                ('doimiy_viloyat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.viloyat', verbose_name='Doimiy yashash viloyati')),
                ('jins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jins', to='myapp.jins', verbose_name='Jinsi')),
                ('millat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='millat', to='myapp.millat', verbose_name='Millat')),
                ('pass_kim_bergan_tuman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='myapp.tuman', verbose_name='Passport bergan tuman')),
                ('talim_shakli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.talimshakli', verbose_name='Ta`lim shakli')),
                ('talim_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.talimturi', verbose_name='Ta`lim turi')),
                ('talim_yunalishi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.yonalishotm', verbose_name='OTM Yo`nalishi')),
            ],
            options={
                'verbose_name': 'Passport ',
                'verbose_name_plural': 'Passportlar',
            },
        ),
    ]
