# Generated by Django 4.0.4 on 2022-05-15 17:45

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavlatMukofoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Davlat mukofoti')),
            ],
            options={
                'verbose_name': 'Davlat mukofoti ',
                'verbose_name_plural': 'Davlat mukofotlari',
            },
        ),
        migrations.AddField(
            model_name='pasport',
            name='davlat_mukofoti_pdf',
            field=models.FileField(blank=True, help_text='PDF file maks. 5 MB', null=True, upload_to='photos/d_mukofot/%Y', validators=[myapp.models.validate_file], verbose_name='Davlat mukofoti pdf shakli'),
        ),
        migrations.AddField(
            model_name='pasport',
            name='harbiy_tavsiyanoma',
            field=models.FileField(blank=True, help_text='PDF file maks. 5MB', null=True, upload_to='photos/harbiy/%Y', validators=[myapp.models.validate_file], verbose_name='Harbiy tavsiyanoma'),
        ),
        migrations.AddField(
            model_name='pasport',
            name='ielts_sertifikat',
            field=models.ImageField(blank=True, help_text='Rasm maks. 5MB', null=True, upload_to='photos/ielts/%Y', validators=[myapp.models.validate_image], verbose_name='IELTS sertifikati'),
        ),
        migrations.AddField(
            model_name='pasport',
            name='davlat_mukofoti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.davlatmukofoti', verbose_name='Davlat mukofoti'),
        ),
    ]
