# Generated by Django 3.1.1 on 2022-05-16 08:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220516_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasport',
            name='doimiy_tuman',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='viloyat', on_delete=django.db.models.deletion.CASCADE, to='myapp.tuman'),
        ),
    ]
