# Generated by Django 3.1.1 on 2022-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220516_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='talimturi',
            name='talim_turi',
            field=models.ManyToManyField(blank=True, to='myapp.TalimShakli', verbose_name='Talim Shakli'),
        ),
    ]
