# Generated by Django 3.1.1 on 2022-05-16 10:00

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20220516_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasport',
            name='talim_yunalishi',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='talim_shakli', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.yonalishotm', verbose_name='OTM Yo`nalishi'),
        ),
    ]
