# Generated by Django 3.1.1 on 2022-05-17 04:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20220516_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasport',
            name='talim_turi',
        ),
        migrations.AlterField(
            model_name='pasport',
            name='talim_yunalishi',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='talim_shakli', chained_model_field='talim_shakli', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.yonalishotm', verbose_name='OTM Yo`nalishi'),
        ),
    ]
